name: Build miasst

on:
  push:
    paths:
      - miasst.c
  pull_request:
    paths:
      - miasst.c
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Tag & Release
      run: |
        VERSION=$(grep -oP '#define VERSION "\K[^"]+' miasst.c)
        if ! git ls-remote --tags origin | grep -q "$VERSION"; then
          git tag "$VERSION"
          git push origin "$VERSION"
        else
          echo "Tag $VERSION already exists, skipping tag creation."
        fi
        awk -v ver="$VERSION" '$0=="## " ver {f=1; next} /^## / {f=0} f' CHANGELOG.md > release_notes.md
        if ! gh release view $VERSION; then
          gh release create $VERSION --title "Release $VERSION" --notes-file release_notes.md
        else
          echo "Release $VERSION already exists, skipping release creation."
        fi
        

    - name: Install Dependencies
      run: |
        docker run --privileged aptman/qus -s -- -p aarch64 arm
        sudo apt-get install -y mingw-w64 libusb-1.0-0-dev libssl-dev libcurl4-openssl-dev
        git clone https://github.com/rafagafe/tiny-json.git
        curl -L -o openssl.zip https://www.firedaemon.com/download-firedaemon-openssl-4-0-zip && 7z x openssl.zip -o./openssl_raw && mkdir -p openssl && mv openssl_raw/x64 openssl/x64
        curl -L -o libusb.7z https://github.com/libusb/libusb/releases/download/v1.0.27/libusb-1.0.27.7z && 7z x libusb.7z -o./libusb && rm libusb.7z
        curl -L -o curl64.zip https://curl.se/windows/dl-8.21.0_7/curl-8.21.0_7-win64-mingw.zip && 7z x curl64.zip -o./curl && rm curl64.zip && mv curl/curl-8.21.0_7-win64-mingw curl/win64

    - name: Build for Windows
      run: |
        x86_64-w64-mingw32-gcc -o miasst_windows64.exe miasst.c tiny-json/tiny-json.c \
          -I./libusb/include -I./openssl/x64/include -I./curl/win64/include -I./tiny-json \
          -L./libusb/MinGW64/static -L./openssl/x64/lib -L./curl/win64/lib \
          -lusb-1.0 -lssl -lcrypto -lcurl -lws2_32 -lbcrypt

    - name: Bundle Windows DLLs
      run: |
        mkdir -p bundle64
        cp miasst_windows64.exe bundle64/
        cp openssl/x64/bin/libcrypto-4-x64.dll openssl/x64/bin/libssl-4-x64.dll bundle64/
        cp curl/win64/bin/libcurl-x64.dll bundle64/
        cp libusb/MinGW64/dll/libusb-1.0.dll bundle64/
        (cd bundle64 && zip -r ../miasst_windows64.zip .)

    - name: Build miasst for Termux
      run: |
        for arch in arm aarch64; do
          docker run --name $arch --privileged \
            -v $(pwd)/miasst.c:/data/data/com.termux/files/home/miasst.c \
            -v $(pwd)/tiny-json:/data/data/com.termux/files/home/tiny-json \
            termux/termux-docker:$arch bash -c "yes | pkg install clang && yes | pkg install libusb && yes | pkg install libc++ && clang -o miasst_termux_$arch miasst.c tiny-json/tiny-json.c -I/usr/include/openssl -I. -lssl -lcrypto -lcurl -lusb-1.0"
          docker cp $arch:/data/data/com.termux/files/home/miasst_termux_$arch ./
        done

    - name: Build for Ubuntu
      run: |
        gcc -o miasst_ubuntu miasst.c tiny-json/tiny-json.c \
          -I/usr/include/openssl -I. -lssl -lcrypto -lcurl -lusb-1.0

    - name: Upload
      run: |
        VERSION=$(grep -oP '#define VERSION "\K[^"]+' miasst.c)
        gh release upload $VERSION ./miasst_windows64.zip ./miasst_ubuntu ./miasst_termux_aarch64 ./miasst_termux_arm --clobber

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        brew install libusb openssl curl
        git clone https://github.com/rafagafe/tiny-json.git

    - name: Build miasst for macOS
      run: |
        clang -o miasst_macos miasst.c tiny-json/tiny-json.c -I/System/Volumes/Data/opt/homebrew/Cellar/libusb/1.0.27/include -I/System/Volumes/Data/opt/homebrew/opt/openssl/include -L/System/Volumes/Data/opt/homebrew/Cellar/libusb/1.0.27/lib -L/System/Volumes/Data/opt/homebrew/opt/openssl/lib -I. -lssl -lcrypto -lcurl -lusb-1.0

    - name: Upload macOS Build
      run: |
        VERSION=$(awk -F'"' '/#define VERSION/ {print $2}' miasst.c)
        gh release upload $VERSION ./miasst_macos --clobber
